name: Build & Push Docker (Docker Hub)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - '.github/workflows/docker.yml'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force rebuild even without changes'
        required: false
        default: false
        type: boolean

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/comfyui-runpod
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/comfyui-runpod:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and export to Docker (for testing)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Test Docker Image
        if: github.event_name == 'pull_request'
        run: |
          # Basis-Test: Container startet
          docker run --rm -d --name test-container ${{ env.TEST_TAG }}
          sleep 10
          
          # Prüfe ob Container läuft
          docker ps | grep test-container
          
          # Prüfe Logs auf Fehler
          docker logs test-container 2>&1 | grep -i error || true
          
          # Cleanup
          docker stop test-container || true

      - name: Build & Push Production
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:$(date +%Y%m%d)
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=${{ github.sha }}
            VERSION=${{ github.run_number }}

      - name: Update Docker Hub Description
        if: github.event_name != 'pull_request' && success()
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/comfyui-runpod
          readme-filepath: ./README.md